import { Providers } from "@/components/providers/Provider";
import { Sidebar } from "@/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex flex-col md:flex-row min-h-screen w-full">
            <Sidebar />
            <main className="flex-1 bg-gray-100 w-full">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
